export const TR = {
    genel: {
        yukluyor: 'Yükleniyor...',
        kaydet: 'Kaydet',
        iptal: 'İptal',
        onayla: 'Onayla',
        reddet: 'Reddet',
        sil: 'Sil',
        duzenle: 'Düzenle',
        ekle: 'Ekle',
        ara: 'Ara',
        filtrele: 'Filtrele',
        hata: 'Hata oluştu',
        basarili: 'Başarılı',
        uyari: 'Uyarı',
        kapat: 'Kapat',
        gonder: 'Gönder',
        yenile: 'Yenile',
        detay: 'Detay',
        para: (val: number) =>
            `₺${Number(val).toLocaleString('tr-TR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
        yuzde: (val: number) => `%${(val * 100).toFixed(1)}`,
        kdvLabel: (oran: number) => `KDV %${oran}`,
    },
    auth: {
        girisYap: 'Giriş Yap',
        cikisYap: 'Çıkış Yap',
        kayitOl: 'Kayıt Ol',
        eposta: 'E-posta',
        sifre: 'Şifre',
        adSoyad: 'Ad Soyad',
        hesabinizYokMu: 'Hesabınız yok mu?',
        zatenHesabinizVarMi: 'Zaten hesabınız var mı?',
        girisHatasi: 'Giriş başarısız. E-posta veya şifre hatalı.',
        kayitBasarili: 'Kayıt başarılı. Giriş yapabilirsiniz.',
    },
    kenarCubugu: {
        strateji: '1. Strateji',
        trendAI: '2. Trend AI',
        koleksiyon: '3. Koleksiyon',
        tema: '4. Tema & Mood',
        tasarim: '5. Tasarım',
        malzeme: '6. Kumaş & Malzeme',
        maliyetlendirme: '7. Maliyetlendirme',
        ornekleme: '8. Örnekleme',
        uretim: '9. Üretim',
        analiz: '10. Analiz',
        admin: '11. Yönetim',
        ayarlar: 'Ayarlar',
        cikisYap: 'Çıkış Yap',
    },
    strateji: {
        baslik: 'Sezon Stratejisi',
        aciklama: 'Sezonları yönetin, bütçe ve SKU hedeflerini belirleyin.',
        yeniSezon: 'Yeni Sezon Oluştur',
        sezonAdi: 'Sezon Adı',
        butce: 'Bütçe (₺)',
        skuHedefi: 'SKU Hedefi',
        baslamaTarihi: 'Başlama Tarihi',
        bitisTarihi: 'Bitiş Tarihi',
        hedefMarj: 'Hedef Marj (%)',
        minButceHatasi: 'Minimum bütçe ₺10.000 olmalıdır.',
        durum: { PLANNED: 'Planlandı', ACTIVE: 'Aktif', ARCHIVED: 'Arşivlendi' },
        butceKullanimi: 'Bütçe Kullanımı',
        skuSayisi: 'SKU Sayısı',
        ortMarj: 'Ort. Marj',
        sezonlar: 'Sezonlar',
        sezonYok: 'Henüz sezon oluşturulmamış.',
        olusturuldu: 'Sezon başarıyla oluşturuldu.',
    },
    koleksiyon: {
        baslik: 'Koleksiyon Mimarisi',
        aciklama: 'Sezon için kategori ve SKU planlamasını yapın.',
        kategoriEkle: 'Kategori Ekle',
        skuEkle: 'SKU Ekle',
        kategori: 'Kategori',
        urunAdi: 'Ürün Adı',
        renk: 'Renk',
        kumas: 'Kumaş',
        tedarikciSehri: 'Tedarikçi Şehri',
        kategoriler: [
            'Elbise', 'Bluz', 'Pantolon', 'Dış Giyim',
            'Triko', 'Denim', 'Aksesuar', 'Etek', 'Şort', 'Tulum',
        ],
        fiyatNoktaları: {
            ENTRY: 'Giriş (₺500-₺1.500)',
            CORE: 'Çekirdek (₺1.500-₺3.000)',
            PREMIUM: 'Premium (₺3.000+)',
        },
        sezonSecin: 'Sezon Seçin',
        sezonSecilmedi: 'Lütfen önce bir sezon seçin.',
        slotBos: 'SKU Ekle',
        eklendi: 'SKU başarıyla eklendi.',
    },
    tasarim: {
        baslik: 'Tasarım Stüdyosu',
        remixBaslik: 'Remix İstasyonu',
        malzemeSecin: 'Malzeme Seçin',
        variasyonOlustur: '✨ Varyasyon Oluştur',
        remixYapiliyor: '⚡ Remix Yapılıyor...',
        remixMaliyeti: 'Stable Diffusion XL • Tahmini: ~₺1.20',
        eskizYukle: 'Eskiz Yükle',
        eskizSecilmedi: 'Lütfen bir eskiz yükleyin.',
        girdi: 'Girdi: Eskiz',
        cikti: 'Çıktı: Remix',
        sifirla: 'Sıfırla',
        malzemeSecilmedi: 'Lütfen bir malzeme seçin.',
    },
    maliyet: {
        baslik: 'Maliyetlendirme',
        aciklama: 'Tasarım bazında maliyet hesapla, KDV ekle ve onayla.',
        tasarimSec: 'Tasarım Seç',
        kumasFiyati: 'Kumaş Fiyatı (₺/mt)',
        kumasYieldi: 'Kumaş Sarfiyatı (mt)',
        dikimUcreti: 'Dikim Ücreti (₺)',
        lojistik: 'Lojistik (₺)',
        gumrukVergisi: 'Gümrük Vergisi (%)',
        kdvOrani: 'KDV Oranı',
        hesapla: 'Maliyet Hesapla',
        maliyet: 'Maliyet',
        hedefPerakende: 'Hedef Perakende (KDV Hariç)',
        kdvDahilFiyat: 'KDV Dahil Fiyat',
        toptanFiyat: 'Toptan Fiyat',
        brütMarj: 'Brüt Marj',
        marjUyarisi: '⚠ Marj hedefin altında. Kumaş maliyetini yeniden görüşün.',
        onaylaButon: 'Maliyet Tablosunu Onayla',
        onaylandi: 'Maliyet tablosu onaylandı.',
        hesaplandi: 'Maliyet başarıyla hesaplandı.',
    },
    trend: {
        baslik: 'Trend Analizi',
        aciklama: 'Yapay zeka ile sezon trend raporu oluşturun.',
        raporOlustur: 'Rapor Oluştur',
        sorguPlaceholder: 'Örn: İlkbahar/Yaz 2026 - Akdeniz Esintisi',
        olusturuluyor: 'Rapor hazırlanıyor...',
        ozet: 'Sezon Özeti',
        anahtarKelimeler: 'Anahtar Kelimeler',
        renkPaleti: 'Renk Paleti',
        kumasOnerileri: 'Kumaş Önerileri',
        kategoriOnerileri: 'Kategori Önerileri',
        tedarikMerkezi: 'Tedarik Merkezi',
        oncelik: { YUKSEK: 'Yüksek', ORTA: 'Orta', DUSUK: 'Düşük' },
        sorguBos: 'Lütfen sezon ve tema girin.',
        raporHazir: 'Trend raporu hazır.',
    },
    analiz: {
        baslik: 'Performans Analizi',
        aciklama: 'Sezon performansını analiz edin ve gelecek sezon için öneriler alın.',
        gorusAl: 'Yapay Zeka Görüşü Al',
        sezonSecin: 'Sezon Seçin',
        enIyiPerformancilar: 'En İyi Performanscılar',
        dusukPerformancilar: 'Düşük Performanscılar',
        gorusler: 'Yapay Zeka Görüşü',
        gelecekSezonOnerileri: 'Gelecek Sezon Önerileri',
        kategoriInsight: 'Kategori Analizi',
        yukluyor: 'Analiz yapılıyor...',
        sezonSecilmedi: 'Lütfen analiz için bir sezon seçin.',
    },
    ayarlar: {
        baslik: 'Kullanıcı Ayarları',
        yapayZeka: 'Yapay Zeka Sağlayıcısı',
        apiAnahtari: 'API Anahtarı',
        saglaycılar: {
            GEMINI: 'Google Gemini',
            OPENAI: 'OpenAI GPT',
            CLAUDE: 'Anthropic Claude',
        },
        kaydet: 'Ayarları Kaydet',
        anahtarKaydedildi: 'API anahtarı güvenli şekilde kaydedildi.',
        mevcutSaglayici: 'Mevcut sağlayıcı',
        anahtarIpucu: 'Anahtarınız şifreli olarak saklanır ve yalnızca sizin işlemleriniz için kullanılır.',
        anahtarPlaceholder: 'API anahtarınızı buraya girin...',
        varsayilan: 'Sunucu varsayılanı (Gemini)',
    },
    agui: {
        bekliyor: 'Bekliyor',
        dusunuyor: 'Düşünüyor...',
        bloke: 'İşlem Engellendi',
        uyari: 'Uyarı',
        baslik: 'AG-UI KORUYUCU',
    },
    onay: {
        onayla: 'Onayla',
        reddet: 'Reddet',
        onayNotu: 'Onay notu (isteğe bağlı)',
        onaylandi: 'Başarıyla onaylandı.',
        reddedildi: 'Reddedildi.',
        yetkiYok: 'Bu işlem için yetkiniz bulunmamaktadır.',
    },
} as const;

export type TrKeys = typeof TR;
